"""Initial Migration

Revision ID: 614b41822c5b
Revises: 
Create Date: 2020-12-13 12:28:07.871462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614b41822c5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
